### LOGIN user
POST http://localhost:5000/user/signin
Content-Type: application/json

{
    "email":"A@gmail.com",
    "password":"a"
}


### SEE NOTIF user
GET http://localhost:5000/user/inboxNotifications/5fc8499c3b2c50129ccca6d1
Content-Type: application/json
access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmM4NDk5YzNiMmM1MDEyOWNjY2E2ZDEiLCJpYXQiOjE2MDY5NjE5NjZ9.cGw_xEwOaksSIA6mivDmRwxKbBKLEQ_J9xZr-rC4RM0


### SEE INBOX user
GET http://localhost:5000/user/inbox/5fc8499c3b2c50129ccca6d1
Content-Type: application/json
access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmM4NDk5YzNiMmM1MDEyOWNjY2E2ZDEiLCJpYXQiOjE2MDY5NjE5NjZ9.cGw_xEwOaksSIA6mivDmRwxKbBKLEQ_J9xZr-rC4RM0


### Tournament Rules
POST http://localhost:5000/comittee/createRules/5fd0b0291ad02c425044c659
Content-Type: application/json
access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmQwYjAyOTFhZDAyYzQyNTA0NGM2NTkiLCJpYXQiOjE2MDc1NDI0NDJ9.8xE1TpuYdyvdESBddJ5sPAqG4ehuxsfRu76Da_atBcY

{
    "age":23,
    "subdistrict":"jelambar",
    "minParticipant":4,
    "maxParticipant":8
}



### Create Tournament
POST http://localhost:5000/comittee/createGame/5fd0b0291ad02c425044c659
Content-Type: application/json
access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmQwYjAyOTFhZDAyYzQyNTA0NGM2NTkiLCJpYXQiOjE2MDc1NDI0NDJ9.8xE1TpuYdyvdESBddJ5sPAqG4ehuxsfRu76Da_atBcY

{
    "tournamentName":"csgo",
    "tournamentOpen":"2021-12-20",
    "tournamentStart":"2021-12-25",
    "tournamentClose":"2021-12-28",
    "tournamentType":"freeforall",
    "rulesName":"23_1_jelambar",
    "groupEntry":false
}

### SEE notification
GET http://localhost:5000/user/inboxNotifications/5fd0b0291ad02c425044c659
Content-Type: application/json
access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmQwYjAyOTFhZDAyYzQyNTA0NGM2NTkiLCJpYXQiOjE2MDc1NDI0NDJ9.8xE1TpuYdyvdESBddJ5sPAqG4ehuxsfRu76Da_atBcY


### SEE inbox
GET http://localhost:5000/user/inbox/5fd0b0291ad02c425044c659
Content-Type: application/json
access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmQwYjAyOTFhZDAyYzQyNTA0NGM2NTkiLCJpYXQiOjE2MDc1NDI0NDJ9.8xE1TpuYdyvdESBddJ5sPAqG4ehuxsfRu76Da_atBcY



### APPROVE group AUTOMATICALLY through inbox
PUT http://localhost:5000/comittee/approve/5fd0b0291ad02c425044c659
Content-Type: application/json
access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmQwYjAyOTFhZDAyYzQyNTA0NGM2NTkiLCJpYXQiOjE2MDc1NDI0NDJ9.8xE1TpuYdyvdESBddJ5sPAqG4ehuxsfRu76Da_atBcY

{
    "participant":[
        {
        "_groupId":"5fd2756c21692d48847c2cf7"  
    }
    ],
    "_tournamentId":"5fd3abe80db961494422a610"
}



### APPROVE user AUTOMATICALLY through inbox
PUT http://localhost:5000/comittee/approve/5fd0b0291ad02c425044c659
Content-Type: application/json
access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmQwYjAyOTFhZDAyYzQyNTA0NGM2NTkiLCJpYXQiOjE2MDc1NDI0NDJ9.8xE1TpuYdyvdESBddJ5sPAqG4ehuxsfRu76Da_atBcY

{
    "participant":[
        {
        "_userId":"5fd1941ad95e6f444c0148dc"  
        }
    ],
    "_tournamentId":"5fd3abe80db961494422a610"
}