### LOGIN user
POST http://localhost:3000/user/signin
Content-Type: application/json

{
    "email":"elonMusk@gmail.com",
    "password":"ghijklmne"
}


### assign Committee
PUT http://localhost:3000/Head/assign/5fbd4e18a768701d88a7c10d
Content-Type: application/json
access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmJkNGUxOGE3Njg3MDFkODhhN2MxMGQiLCJpYXQiOjE2MDYyNzUyNzF9.BulmMN7aJlyjvddJAX-AB6LFRhoi4XFmnOBiMjaE0PQ

{
    "userId":"5fbd4efca768701d88a7c10f"
}