
### SEE list
GET http://localhost:5000/comittee/seeList/5fd0b0291ad02c425044c659
Content-Type: application/json
access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmQwYjAyOTFhZDAyYzQyNTA0NGM2NTkiLCJpYXQiOjE2MDc1NDI0NDJ9.8xE1TpuYdyvdESBddJ5sPAqG4ehuxsfRu76Da_atBcY

{
    "_id":"5fd3abe80db961494422a611"
}




### PUT SCORE participant per person
PUT http://localhost:5000/comittee/putScore/5fd0b0291ad02c425044c659
Content-Type: application/json
access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmQwYjAyOTFhZDAyYzQyNTA0NGM2NTkiLCJpYXQiOjE2MDc1NDI0NDJ9.8xE1TpuYdyvdESBddJ5sPAqG4ehuxsfRu76Da_atBcY

{
    "_id":"5fd3abe80db961494422a611",
    "_userId":"5fd6580ed95e6f444c0148f7",
    "score":42
}



### START BRANCHES
PUT http://localhost:5000/comittee/proceedTournament/5fd0b0291ad02c425044c659
Content-Type: application/json
access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmQwYjAyOTFhZDAyYzQyNTA0NGM2NTkiLCJpYXQiOjE2MDc1NDI0NDJ9.8xE1TpuYdyvdESBddJ5sPAqG4ehuxsfRu76Da_atBcY

{
    "_id":"5fd78baf3d406b4b946a48a9"
}