
### SEE list
GET http://localhost:5000/comittee/seeList/5fd0b0291ad02c425044c659
Content-Type: application/json
access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmQwYjAyOTFhZDAyYzQyNTA0NGM2NTkiLCJpYXQiOjE2MDc1NDI0NDJ9.8xE1TpuYdyvdESBddJ5sPAqG4ehuxsfRu76Da_atBcY

{
    "_id":"5fd3471a86d2f54d0467306a"
}


### SHUFFLING participant
PUT http://localhost:5000/comittee/shuffle/5fd0b0291ad02c425044c659
Content-Type: application/json
access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmQwYjAyOTFhZDAyYzQyNTA0NGM2NTkiLCJpYXQiOjE2MDc1NDI0NDJ9.8xE1TpuYdyvdESBddJ5sPAqG4ehuxsfRu76Da_atBcY

{
    "_id":"5fd371e25ba3d45188c6aa71"
}


### BRANCHES participant
PUT http://localhost:5000/comittee/branches/5fd0b0291ad02c425044c659
Content-Type: application/json
access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmQwYjAyOTFhZDAyYzQyNTA0NGM2NTkiLCJpYXQiOjE2MDc1NDI0NDJ9.8xE1TpuYdyvdESBddJ5sPAqG4ehuxsfRu76Da_atBcY

{
    "_id":"5fd3abe80db961494422a611"
}