### test
POST http://localhost:3000/user/signup
Content-Type: application/json
# go to postman


### LOGIN user
POST http://localhost:3000/user/signin
Content-Type: application/json

{
    "email":"talktomeself@gmail.com",
    "password":"ghijklmne",
    "verifyingToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MDYyNDIwNDJ9.kWXhlI7lQPUsLcCbkxSXQ6i2Ov5JVRHFgXLbkM0puz8"
}


### see inbox
GET http://localhost:3000/user/inbox/5fbc70f7a484c65004b44106
Content-Type: application/json
access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmJjNzBmN2E0ODRjNjUwMDRiNDQxMDYiLCJpYXQiOjE2MDYxODUzMjl9.dT9qTuiYQE6BcyCt7jAI1yZH1kXY9M9-1UOhMjUx2do


### see profile
GET http://localhost:3000/user/profile/5fbc70f7a484c65004b44106
Content-Type: application/json
access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmJjNzBmN2E0ODRjNjUwMDRiNDQxMDYiLCJpYXQiOjE2MDYxODUzMjl9.dT9qTuiYQE6BcyCt7jAI1yZH1kXY9M9-1UOhMjUx2do


### change profile
PUT  http://localhost:3000/user/profile/5fbc70f7a484c65004b44106
Content-Type: application/json
access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmJjNzBmN2E0ODRjNjUwMDRiNDQxMDYiLCJpYXQiOjE2MDYxODUzMjl9.dT9qTuiYQE6BcyCt7jAI1yZH1kXY9M9-1UOhMjUx2do

{
    "fullname":"terara"
}