### test
POST http://localhost:5000/user/signup
Content-Type: application/json

{
    "email":"naufalibnu75@gmail.com",
    "username":"user",
    "password":"a"
}


### signin
POST http://localhost:5000/user/signin
Content-Type: application/json


{
    "email":"naufalibnu75@gmail.com",
    "password":"a",
    "verifyingToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MDcyMzY3NzB9.cjbGr1LlK9Hwn-3pJV7aydwUFj6KEBawNEEXYVrc9kM"
}

### Forgot Password
POST http://localhost:5000/user/forget
Content-Type: application/json


{
    "email":"naufalibnu75@gmail.com",
}





### See Tournament
GET http://localhost:5000/Gamewhatthefuckyouwant
Content-Type: application/json


