
### LOGIN user
POST http://localhost:5000/user/signin
Content-Type: application/json

{
    "username":"b",
    "password":"abc"
}


### SEE profile
GET http://localhost:5000/user/profile/5fd10555249a1e08745312c6
Content-Type: application/json
access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmQxMDU1NTI0OWExZTA4NzQ1MzEyYzYiLCJpYXQiOjE2MDc1NzMzNzZ9.CA57QwuPNwhuVc6864xbRxfwwJBoSfynmIot4DI4G9U


### EDIT profile
PUT http://localhost:5000/user/profile/5fd10555249a1e08745312c6
Content-Type: application/json
access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmQxMDU1NTI0OWExZTA4NzQ1MzEyYzYiLCJpYXQiOjE2MDc1NzMzNzZ9.CA57QwuPNwhuVc6864xbRxfwwJBoSfynmIot4DI4G9U

{
   "fullname":"samuji parangin" 
}


### SUBMIT participation
POST http://localhost:5000/user/submit/5fd10555249a1e08745312c6
Content-Type: application/json
access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmQxMDU1NTI0OWExZTA4NzQ1MzEyYzYiLCJpYXQiOjE2MDc1NzMzNzZ9.CA57QwuPNwhuVc6864xbRxfwwJBoSfynmIot4DI4G9U

{
    "_CommitteeId":"5fd0b0291ad02c425044c659",
    "message":"pubg"
}


### SUBMIT group
POST http://localhost:5000/user/submitGroup/5fd10555249a1e08745312c6
Content-Type: application/json
access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmQxMDU1NTI0OWExZTA4NzQ1MzEyYzYiLCJpYXQiOjE2MDc1NzMzNzZ9.CA57QwuPNwhuVc6864xbRxfwwJBoSfynmIot4DI4G9U

{
    "_CommitteeId":"5fd0b0291ad02c425044c659",
    "message":["dota","Cruxiates","5fd19319d95e6f444c0148d7","5fd1936fd95e6f444c0148da"]
}


### SEE notification
GET http://localhost:5000/user/inboxNotifications/5fd10555249a1e08745312c6
Content-Type: application/json
access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmQxMDU1NTI0OWExZTA4NzQ1MzEyYzYiLCJpYXQiOjE2MDc1NzMzNzZ9.CA57QwuPNwhuVc6864xbRxfwwJBoSfynmIot4DI4G9U


### SEE inbox
GET http://localhost:5000/user/inbox/5fd10555249a1e08745312c6
Content-Type: application/json
access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmQxMDU1NTI0OWExZTA4NzQ1MzEyYzYiLCJpYXQiOjE2MDc1NzMzNzZ9.CA57QwuPNwhuVc6864xbRxfwwJBoSfynmIot4DI4G9U



### CREATE group
POST http://localhost:5000/user/createGroup/5fd10555249a1e08745312c6
Content-Type: application/json
access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmQxMDU1NTI0OWExZTA4NzQ1MzEyYzYiLCJpYXQiOjE2MDc1NzMzNzZ9.CA57QwuPNwhuVc6864xbRxfwwJBoSfynmIot4DI4G9U

{
      "groupName":"cruxiates"
}



### DELETE group
DELETE http://localhost:5000/user/demolishGroup/5fd10555249a1e08745312c6
Content-Type: application/json
access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmQxMDU1NTI0OWExZTA4NzQ1MzEyYzYiLCJpYXQiOjE2MDc1NzMzNzZ9.CA57QwuPNwhuVc6864xbRxfwwJBoSfynmIot4DI4G9U

{
      "_id":"5fd5984cadd4e049543cf761"
}




### RECRUIT group
PUT http://localhost:5000/user/groupRecruit/5fd10555249a1e08745312c6
Content-Type: application/json
access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmQxMDU1NTI0OWExZTA4NzQ1MzEyYzYiLCJpYXQiOjE2MDc1NzMzNzZ9.CA57QwuPNwhuVc6864xbRxfwwJBoSfynmIot4DI4G9U

{   
      "member":[
          {
              "_userId":"5fd19319d95e6f444c0148d7"
        }
      ]  
}



### KICK group
PUT http://localhost:5000/user/groupRecruit/5fd10555249a1e08745312c6
Content-Type: application/json
access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmQxMDU1NTI0OWExZTA4NzQ1MzEyYzYiLCJpYXQiOjE2MDc1NzMzNzZ9.CA57QwuPNwhuVc6864xbRxfwwJBoSfynmIot4DI4G9U

{   
      "member":[
          {
              "_userId":"5fd19319d95e6f444c0148d7"
        }
      ]  
}